name: Publish to GKE
on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  main:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
    env:
      GCLOUD_PROJECT_ID: '（プロジェクトID）'
      GCLOUD_WORKLOAD_IDENTITY: '（Workload Identity 連携）'
      GCLOUD_REGION: 'asia-northeast1'
      CLOUD_ARTIFACT_REGISTRY: '（Artifact Registry リポジトリー）'
      DNS_DOMAIN: '（ドメイン）'
      DOCKER_IMAGE: 'gh-book-image'
      GCLOUD_GKE_CLUSTER: 'github-actions-book-cluster'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: './src'
        token: ${{ secrets.GH_TOKEN }}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set DNS and docker image tag and namespace
      run: |
        echo 'TARGET_DOMAIN=${{ steps.branch-name.outputs.current_branch }}.gke.${{ env.DNS_DOMAIN }}' >> $GITHUB_ENV
        echo 'TARGET_DOCKER_IMAGE_TAG=${{ env.CLOUD_ARTIFACT_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.branch-name.outputs.current_branch }}' >> $GITHUB_ENV

    - id: auth
      name: Set up GoogleCloud Authorization
      uses: google-github-actions/auth@v0
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.GCLOUD_WORKLOAD_IDENTITY }}
        service_account: 'github-actions@${{ env.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com'
        access_token_lifetime: '300s'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GCLOUD_GKE_CLUSTER }}
        location: ${{ env.GCLOUD_REGION }}

    - name: Build docker image
      run: |
        cd ./src/dynamic
        gcloud builds submit --config=cloudbuild.yaml --substitutions=TAG_NAME=${{ env.TARGET_DOCKER_IMAGE_TAG }}

    - name: Apply kubernetes configuration
      if: ${{ github.event.action != 'synchronize' }}
      run: |
        cd ./src/dynamic
        sed -e 's!DEPLOY_IMAGE!${{ env.TARGET_DOCKER_IMAGE_TAG }}!g' -e 's!BRANCH_NAME!${{ steps.branch-name.outputs.current_branch }}!g' -e 's!DOMAIN_NAME!${{ env.TARGET_DOMAIN }}!g' kubernetes.yaml | kubectl apply -f -

    - name: Rollout restart kubernetes deployment
      if: ${{ github.event.action == 'synchronize' }}
      run: |
        kubectl rollout restart deployments/${{ steps.branch-name.outputs.current_branch }}-deployment